### ISSUE TITLE
RubyInstaller2 mirror always returns status code 308

### ISSUE THREAD

**Issue by ccmywish** [sjtug/mirror-docker-unified#378] opened 2023-05-01 23:03 UTC
For example：

Link is 
- https://mirror.sjtu.edu.cn/github-release/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.2.2-1/rubyinstaller-devkit-3.2.2-1-x64.exe 

but redirect to 

- https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/github-release/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.2.2

Many [rbenv for Windows](https://github.com/ccmywish/rbenv-for-windows) users reported that they can't download from PowerShell 5.x series using this link because of the `308 Permanent Redirect` status code. However, clicking this link directly from web browser works fine. 

So, I'm curious why all links redirect to other locations? Could we settle it?

**Comment by ccmywish** [comment] 2023-05-02 17:26
If it is specially designed, please close this issue and I'll try to fix that from our client.

**Comment by PhotonQuantum** [comment] 2023-06-01 06:50
Yes, this is intended behavior. We use S3 storage for some repositories and redirect users to its HTTP endpoint for download requests. 

Closing for now. Feel free to reopen it if you have further questions.

**Closed by PhotonQuantum** 2023-06-01 06:50 UTC
